STA-Development/BEP_FE

.github/CODEOWNERS
=> feat: add Arsen and Gor to codeowners

pnpm-lock.yaml, src/components/Container/Container.tsx, src/components/Container/index.tsx, src/components/Content/Content.stories.tsx, src/components/Footer/Footer.tsx, src/components/Header/Header.tsx, src/layouts/ProfileLayout.tsx, src/pages/_error.tsx, src/pages/about-us/index.tsx, src/pages/contact-us/index.tsx, src/pages/fill-the-form/index.tsx, src/pages/index.tsx, src/pages/login/index.tsx, src/pages/monitoring-systems/index.tsx, src/pages/news/index.tsx, src/pages/register/index.tsx, src/pages/reset-password/index.tsx
=> FEAT Create Conatiner component

pnpm-lock.yaml, src/layouts/ProfileLayout.tsx, src/pages/_app.tsx
=> FIX: layout logic, update lock after package lock change

src/components/Modals/Application/AddApplicationModal/index.tsx, src/components/Modals/Application/DeleteApplicationModal/index.tsx, src/components/Modals/Modal.tsx, src/components/Modals/index.tsx
=> Create global component for modals

src/components/Modals/Modal.tsx, src/pages/_app.tsx
=> FIX: Global fonts v2

src/components/SearchHeader/index.tsx
=> FIX: resolve issue in autocomplete file

src/components/RedirectionHandler/RedirectionHandler.tsx, src/pages/_app.tsx, src/redux/slices/views/middleware.ts
=> [BF-61] Redirection logic by views' middleware

src/components/Breadcrumbs/Breadcrumbs.tsx, src/pages/contact-us/index.tsx, src/ui-components/Input/Input.tsx
=> Fix: Contact-us styles

pnpm-lock.yaml
=> Fix : yarn-lock error

next.config.js, src/manager/events/eventsManager.ts, src/pages/events/[id].tsx, src/pages/events/index.tsx, src/redux/slices/events/initialState.ts, src/redux/slices/events/middleware.ts, src/redux/slices/events/reducers.ts, src/redux/slices/events/selector.ts, src/types/reduxTypes/eventsStateTypes.ts
=> [BF-65] FEAT: Single event page BE integration

src/pages/login/index.tsx, src/pages/register/index.tsx, src/ui-components/FormFields/CheckBox.tsx, src/ui-components/FormFields/TextField.tsx
=> [BF-80] FEAT: Update Controller to useController

src/components/Icons/CloseIcon.tsx
=> FIX: Change mobile header close icon color from white to primary

next.config.js, src/assets/localization/en.json, src/components/IndividualCarousel/index.tsx, src/pages/educational-institutes/[id].tsx, src/redux/slices/educational-instutions/middleware.ts, src/redux/slices/educational-instutions/reducers.ts
=> FIX: educational institute single page

src/components/Modals/Application/AddApplicationModal/index.tsx, src/pages/fill-the-form/index.tsx, src/pages/profile/applications/index.tsx, src/redux/slices/users/middleware.ts
=> FIX: resolve code issues

src/components/Educationalnstitutes/Filters.tsx, src/pages/educational-institutes/index.tsx, src/styles/globals.css
=> FIX: Educational institutes ui

src/components/Icons/LocationIcon.tsx, src/pages/educational-institutes/[id].tsx, src/pages/educational-institutes/index.tsx, src/pages/events/[id].tsx, src/pages/events/index.tsx, src/pages/news/[id].tsx, src/pages/profile/applications/index.tsx, src/pages/profile/settings/index.tsx
=> FIX: some ui and functional issues

src/assets/localization/en.json, src/components/Footer/Footer.tsx, src/components/Header/Header.tsx, src/constants/translations.ts
=> [BF-105] Updating footer and header menu

src/layouts/ProfileLayout.tsx, src/pages/profile/applications/index.tsx
=> Fix profile layout and application list style

src/Middleware.tsx, src/constants/router.ts, src/layouts/LayoutController.tsx, src/layouts/index.tsx, src/manager/axiosInstance.ts, src/pages/_app.tsx
=> FEATURE: Improve redirection logic

src/assets/localization/arm.json, src/assets/localization/en.json, src/assets/localization/ru.json, src/components/Header/Header.tsx, src/components/Header/NotificationList.tsx, src/components/Header/index.tsx, src/components/Icons/NotificationIcon.tsx, src/constants/translations.ts
=> Create notifications component

src/pages/reset-password/index.tsx, src/redux/slices/applications/middleware.ts
=> Fix build error

.github/workflows/deployment.yml
=> FIX: pnpm versio update

src/components/Admin/Common/SharedCRU.tsx
=> fix: On the news page, move the image to the center

src/Middleware.tsx, src/constants/router.ts
=> Fix deactivated user can not login

src/constants/home.tsx, src/pages/index.tsx
=> BF-123 Fix: Home component refactoring

src/components/Header/NotificationList.tsx, src/manager/jobSeeker/jobSeeker.ts, src/redux/slices/applications/initialState.ts, src/redux/slices/applications/middleware.ts, src/redux/slices/applications/reducers.ts, src/types/reduxTypes/areaSpecializationTypes.ts
=> feature: add notification has seen logic and fix notification error

src/components/Header/Header.tsx, src/components/Header/User.tsx, src/pages/news/index.tsx
fixed news page scroll error bug, header notifications and buttons (exept logout) are hidden for admin now.
=> FIX: news page error while scolling, header view for admin
